title: Seong Hun Lee
logo: /img/profile.png
description: >
I am a PhD student in the SLAMLab at the University of Zaragoza. With my supervisor Dr. Javier Civera, I am conducting research on monocular visual(-inertial) odometry and SLAM since September 2017.

I am interested in real-time algorithms for autonomous ground/air vehicles, 3D object reconstruction, and AR/VR on mobile platforms.
theme: jekyll-theme-minimal
