title: Seong Hun Lee
logo: /img/profile.png
description: I am a PhD student in the SLAMLab at the University of Zaragoza. With my supervisor Dr. Javier Civera, I am conducting research on monocular visual(-inertial) odometry and SLAM. 
theme: jekyll-theme-minimal
