title: Seong Hun Lee
logo: /img/profile.png
description: I am a PhD student in the SLAMLab at the University of Zaragoza. Since September 2017, I have been conducting research on monocular visual(-inertial) odometry and SLAM under the supervision of Dr. Javier Civera. I am interested in real-time algorithms for autonomous ground/air vehicles, 3D object reconstruction, and AR/VR on mobile platforms.
theme: jekyll-theme-minimal
